"""added new profile_image column to users table

Revision ID: 421e697efb20
Revises: d5367e957f96
Create Date: 2026-03-10 15:34:40.175674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421e697efb20'
down_revision = 'd5367e957f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
